baseURL = "https://home.supcik.net/"
languageCode = "en-us"
title = "Jacques's Home"
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

[author]
  name = "Jacques Supcik"

[params]
  dateform        = "2 Jan 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006 15:04"

  # footerLeft = "Powered by <a href=\"http://gohugo.io\">Hugo</a>"
  footerRight = "Theme by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"