baseURL = "https://home.supcik.net/"
languageCode = "en-us"
title = "Jacques's Home"
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

[author]
  name = "Jacques Supcik 3"

