# Workflow to build and deploy home.supcik.net

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.75.1'
          extended: true
      - name: Build
        run: hugo --minify
      - name: Prepare deployment
        run: |
          git config user.email "githubfo@supcik.net"
          git config user.name "Github action"
          git checkout --orphan build
          git rm -rf --cached .
          cp deployment/Dockerfile .
          cp deployment/Caddyfile .
          git add -f Dockerfile Caddyfile public/
          git commit -m "prepare deployment"
      - name: Push to dokku
        uses: dokku/github-action@master
        env:
          CI_COMMIT: build
        with:
          # git_push_flags: '-v'
          git_remote_url: 'ssh://dokku@home.supcik.net:25022/website'
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
